#!/usr/bin/env python3
"""implementation/test_transition_model.py

Verification tests for Submodule 2: transition_model.

Run with:
  /.../nuplan_venv/bin/python implementation/test_transition_model.py

Gates (submodules.md):
- Shape test
- Forward+backward
- Equation oracle (at least one hand-checkable computation)
- Overfit 2 transitions
- Diversity: different actions -> different next_bev
"""

import sys

sys.path.insert(0, '/media/skr/storage/autoresearch/autoresearch-paper/paper/dataset/nuplan-devkit')
sys.path.insert(0, '/media/skr/storage/autoresearch/autoresearch-paper/implementation')

import torch
import torch.nn.functional as F

from transition_model import TransitionModel, TransitionModelLoss


def test_shape_assertions():
    print("=" * 80)
    print("Test 1: Shape Assertions")
    print("=" * 80)

    model = TransitionModel(bev_channels=7, bev_height=224, bev_width=224, action_dim=2, hidden_dim=32)
    batch_size = 4
    bev = torch.rand(batch_size, 7, 224, 224)
    action = torch.randn(batch_size, 2)

    next_bev, done = model(bev, action)

    assert next_bev.shape == bev.shape
    assert done.shape == (batch_size,)
    assert next_bev.dtype == torch.float32 and done.dtype == torch.float32
    assert torch.isfinite(next_bev).all() and torch.isfinite(done).all()
    assert (0.0 <= next_bev).all() and (next_bev <= 1.0).all()
    assert (0.0 <= done).all() and (done <= 1.0).all()

    print(f"✅ next_bev shape: {tuple(next_bev.shape)}")
    print(f"✅ done shape: {tuple(done.shape)}")


def test_forward_backward():
    print("=" * 80)
    print("Test 2: Forward + Backward")
    print("=" * 80)

    model = TransitionModel(bev_channels=7, bev_height=224, bev_width=224, action_dim=2, hidden_dim=32)
    bev = torch.rand(2, 7, 224, 224)
    action = torch.randn(2, 2)

    next_bev, done = model(bev, action)
    loss = next_bev.mean() + done.mean()
    loss.backward()

    grads_ok = True
    for p in model.parameters():
        if p.grad is None or not torch.isfinite(p.grad).all():
            grads_ok = False
            break
    assert grads_ok
    print("✅ backward ok")


def test_equation_oracle_film():
    print("=" * 80)
    print("Test 3: Equation Oracle (FiLM)")
    print("=" * 80)

    # Hand-check FiLM: y = x * gamma + beta.
    # With gamma=1 and beta=2*action, expected y = x + 2*action.
    model = TransitionModel(bev_channels=2, bev_height=16, bev_width=16, action_dim=1, hidden_dim=8)
    model.eval()

    with torch.no_grad():
        model.film.beta_net.weight.fill_(2.0)
        model.film.beta_net.bias.zero_()
        model.film.gamma_net.weight.zero_()
        model.film.gamma_net.bias.fill_(1.0)

    x = torch.ones(1, 32, 2, 2)  # hidden_dim*4=32
    a = torch.tensor([[3.0]])

    with torch.no_grad():
        y = model.film(x, a)

    expected = x + 6.0
    max_err = (y - expected).abs().max().item()
    assert max_err < 1e-6, f"FiLM oracle failed, max_err={max_err}"
    print("✅ FiLM oracle ok")


def test_overfit():
    print("=" * 80)
    print("Test 4: Overfit 2 transitions")
    print("=" * 80)

    # Use a deterministic target generated by a fixed (random) teacher model.
    # This avoids the impossibility of fitting arbitrary random targets through a sigmoid output.
    H = W = 56
    torch.manual_seed(123)

    teacher = TransitionModel(bev_channels=7, bev_height=H, bev_width=W, action_dim=2, hidden_dim=32)
    teacher.eval()

    bev = torch.rand(2, 7, H, W)
    action = torch.randn(2, 2)
    with torch.no_grad():
        target, _ = teacher(bev, action)

    model = TransitionModel(bev_channels=7, bev_height=H, bev_width=W, action_dim=2, hidden_dim=32)
    opt = torch.optim.Adam(model.parameters(), lr=3e-3)
    loss_fn = TransitionModelLoss()

    model.train()
    init = None
    for step in range(400):
        opt.zero_grad()
        pred, _ = model(bev, action)
        loss = loss_fn(pred, target)
        if step == 0:
            init = loss.item()
        loss.backward()
        opt.step()

    model.eval()
    with torch.no_grad():
        pred, _ = model(bev, action)
        final = loss_fn(pred, target).item()

    print(f"init={init:.6f} final={final:.6f}")
    assert final < 0.01


def test_diversity():
    print("=" * 80)
    print("Test 5: Diversity")
    print("=" * 80)

    model = TransitionModel(bev_channels=7, bev_height=224, bev_width=224, action_dim=2, hidden_dim=64)
    model.eval()

    torch.manual_seed(456)
    bev = torch.rand(1, 7, 224, 224)
    action1 = torch.tensor([[1.0, 0.0]], dtype=torch.float32)
    action2 = torch.tensor([[-1.0, 1.0]], dtype=torch.float32)

    with torch.no_grad():
        out1, _ = model(bev, action1)
        out2, _ = model(bev, action2)

    diff = (out1 - out2).abs().mean().item()
    cos = F.cosine_similarity(out1.flatten().unsqueeze(0), out2.flatten().unsqueeze(0)).item()

    print(f"mean_abs_diff={diff:.6f} cosine_sim={cos:.6f}")

    assert diff > 1e-4, "Different actions should change next_bev"


def main():
    print("\n" + "=" * 80)
    print("TRANSITION MODEL TEST SUITE")
    print("=" * 80)

    test_shape_assertions()
    test_forward_backward()
    test_equation_oracle_film()
    test_overfit()
    test_diversity()

    print("=" * 80)
    print("✅✅✅ ALL TESTS PASSED ✅✅✅")
    print("=" * 80)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
